kind = "mobile"
previewPath = "/"
title = "Runner"
version = "1.0.0"
id = "artifacts/runner"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22570

[services.development]
run = "pnpm --filter @workspace/runner run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/runner", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/runner", "run", "serve" ]

[services.env]
PORT = "22570"
BASE_PATH = "/"
